name: Build Kivy APK with Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build APK with Buildozer Docker
        uses: docker://buildozer/android:latest
        with:
          args: "android debug"
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: clock2-apk
          path: ./bin/*.apk
          retention-days: 7